openwisp_firmware_upgrader/migrations/0002_default_permissions.py, openwisp_firmware_upgrader/migrations/__init__.py, openwisp_firmware_upgrader/tests/base/test_models.py, tests/openwisp2/sample_firmware_upgrader/migrations/0002_default_permissions.py, tests/openwisp2/sample_firmware_upgrader/migrations/__init__.py
Operators can:
* view builds and related images
* view mass upgrade operations and related device operations
* view device firmware objects
Administrators can:
* all permission on all objects
Closes #15
=> Add default permissions for operators and administrators #15

openwisp_firmware_upgrader/base/admin.py, openwisp_firmware_upgrader/tests/base/test_admin.py, tests/openwisp2/settings.py
This was causing a 500 internal server error for non-admin users, which
could not edit nor view Devices in the admin dashboard.
Fixes #16
=> [fw-upgrade] Fix invalid multitenant_shared_relations for DeviceFirmware

.travis.yml, openwisp_firmware_upgrader/tests/base/test_admin.py, run-qa-checks
I'm testing this change to save build time since creating a new container and installing all the packages requires time and resources on the side of travis. We'll just have to double check:
1. sample app tests are run as expected
2. coverage is not affected and works properly
@atb00ker @nepython @PabloCastellano @NoumbissiValere @TheOneAboveAllTitan please check this out before it will affect part of your work.
If this approach work we should adopt it on all the modules.
=> [ci] Run sample app tests in same build to reduce build time

README.rst, openwisp_firmware_upgrader/api/views.py, openwisp_firmware_upgrader/tests/test_api.py
Notes:
* json output has changed, now results are now returned in the 'results' key of the dictionary
* An extra sql query is required to count the total number of results
Closes #79
=> [api] Add pagination #79

openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/static/admin/css/firmware-upgrader.css, openwisp_firmware_upgrader/templates/admin/firmware_upgrader/change_form.html, openwisp_firmware_upgrader/tests/test_admin.py
Closed issue by updating the chang_view of BuildAdmin
and adding a new change_form_overriden.html template.
Fixes #25
=> [fw-upgrade] Add button to launch mass upgrade in Build #25

openwisp_firmware_upgrader/tasks.py, openwisp_firmware_upgrader/tests/test_tasks.py
- Added exception handling for "upgrade_firmware"
and "batch_upgrade_operation" tasks
- Fixed minor typographical errors in test_tasks
- Made log warning translatable
Fixes #98
=> [fix] Made celery tasks resilient to failure #98

README.rst, openwisp_firmware_upgrader/api/urls.py, openwisp_firmware_upgrader/urls.py, tests/openwisp2/urls.py
Before:
Users needed to add two entries in the root urls of the project.
After:
Users will need to add just one entry for this module.
=> [refactor] Refactored URL schemes for ease of use

openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/tests/test_models.py
Closes #153 
Problem:
Trying to add a Firmware Build with an empty category but a non-empty OS identifier caused a 500 error.
The problem was in a uniqueness check that got executed before `category` field was validated. The code checked for unique (`category.organization`, `os`) for a build.
With an empty `os` field, this check was skipped (`if not self.os: return`) so the rest of the validation checks ran normally.
This change makes it so that the check is skipped when either `os` or `category` fields are empty. The empty field is caught in the rest of the validation checks and reported to the user. Test for the bug has been added.
=> [models] Fixed 500 error on empty category #153

openwisp_firmware_upgrader/upgraders/openwisp.py, openwisp_firmware_upgrader/upgraders/openwrt.py
The strings used to store log messages in the upgrader class is made translatable using the gettext() or _
Closes #35
=> [fw-upgrade] make strings translatable #35

.github/workflows/ci.yml
Add new python runtime, remove python 3.6 from CI
Fixes #160
=> [ci] Add new python runtime

openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/upgraders/openwrt.py
SSHException is raised by failures in SSH2 protocol negotiation
or logic errors by paramiko module.
Handling for the exception is required to make firmware upgrader
retry connection attempt.
=> [fix] Added exception handling for SSHException

openwisp_firmware_upgrader/tests/test_models.py, openwisp_firmware_upgrader/tests/test_selenium.py, openwisp_firmware_upgrader/tests/test_tasks.py
Used openwisp-utils `@capture_any_output()` to avoid noisy
error logging output during tests, Closes #118
=> [test] Avoided noisy error logging during tests #118

openwisp_firmware_upgrader/tests/test_api.py
In tests, the administrator couldn't view the object because the administrator was not the manager of any organization.
https://github.com/openwisp/openwisp-users/blob/36fae27a9e60fa57f671ff3feb628efb0bfc16b7/openwisp_users/api/permissions.py#L66-L76
Added manager permission by making admin (to view object details).
=> [change] Fixed failing tests

openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/tests/test_models.py
Bug:
The previous code used the "os" module for deleting resisdual
firmware image files. This causes issues when the project uses
a file storage backend other than based on file system.
=> [fix] Use storage backend method for deleting FirmwareImage.file

openwisp_firmware_upgrader/hardware.py
The PC Engines APU2 boards should use the 64bit firmware instead of 32bit.
See https://openwrt.org/toh/pcengines/apu2
I am running APU2 with 64 bit, so I have tested it.
=> PC Engines APU2 should use x86/64 firmware

openwisp_firmware_upgrader/hardware.py
Adding support for Dongwon T&I DW02-412H (128M) / KT GiGA WiFi home (128M)
=> Add Dongwon T&I DW02-412H (128M) / KT GiGA WiFi home (128M)

openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/upgraders/openwrt.py
The test is misssing.
Fixes #235
This may fix also #233 (needs manual testing to confirm).
=> [fix] Fixed issues in reconnecting to device after firmware upgrade #235

openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/templates/admin/firmware_upgrader/device_firmware_inline.html, openwisp_firmware_upgrader/tests/test_admin.py, openwisp_firmware_upgrader/utils.py
Don't log error on device change page if the device does not
have any DeviceConnection objects.
Closes #249
=> [fix] Avoid logging error for Device without DeviceConnection #249 

openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/upgraders/openwrt.py
Added openwisp-config and openwisp-monitoring to the list of non critical services which can be stopped to free up memory.
=> [chores] Updated list of non critical services in OpenWrt upgrader

.github/workflows/ci.yml, openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/api/views.py, openwisp_firmware_upgrader/tests/test_admin.py, openwisp_firmware_upgrader/tests/test_api.py, openwisp_firmware_upgrader/tests/test_models.py, openwisp_firmware_upgrader/tests/test_selenium.py
Do not allow changing DeviceFirmwareImage of a deactivated device.
Closes #251
**Blockers**
=> [change] Added support for device deactivation feature #251

CHANGES.rst, openwisp_firmware_upgrader/__init__.py
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
=> 1.1.0 release

openwisp_firmware_upgrader/tests/test_selenium.py
The test was failing because of changes in openwisp-controller.
https://github.com/openwisp/openwisp-controller/pull/962
=> [tests] Fixed "test_restoring_deleted_device" test

openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/upgraders/openwrt.py
The UUID stored in the config of the openwisp-config agent doesn't have hypens.
=> [chores/fix] Verify valid UUID & accept UUID without dashes
