README.rst
Added travis-ci, coveralls, requires.io badges 
Can Closes #4
=> [firmware-upgrader] Add badges #4

.travis.yml, requirements-test.txt, runflake8, runisort
Configured Travis-CI
Closes #1
=> [firmware-upgrader] Set up travis build and qa checks #1

openwisp_firmware_upgrader/base/admin.py
Allows to go back to previous versions and recover deleted items, added only on builds and categories.
=> [admin] Support reversion on main features

openwisp_firmware_upgrader/base/models.py
=> [upload] Remove build dir if empty #32

.travis.yml, openwisp_firmware_upgrader/apps.py, openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/exceptions.py, openwisp_firmware_upgrader/hardware.py, openwisp_firmware_upgrader/tests/base/__init__.py, openwisp_firmware_upgrader/tests/base/test_admin.py, openwisp_firmware_upgrader/tests/base/test_openwrt_upgrader.py, openwisp_firmware_upgrader/tests/base/test_private_storage.py, openwisp_firmware_upgrader/tests/test_admin.py, openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/tests/test_private_storage.py, openwisp_firmware_upgrader/upgraders/openwrt.py, tests/openwisp2/sample_firmware_upgrader/tests.py
This is only the first step of making the upgrade more robust.
Some tests were missing so I had to add them before being able to introduce further changes with more confidence.
=> More robust upgrades

.travis.yml, README.rst, openwisp_firmware_upgrader/tests/base/test_admin.py, tests/openwisp2/sample_firmware_upgrader/tests.py
Expecting first attempt to fail, on purpose, to double check the test finds errors.
=> [qa] Fixed bug in sample app testing

README.rst, openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/exceptions.py, openwisp_firmware_upgrader/settings.py, openwisp_firmware_upgrader/tasks.py, openwisp_firmware_upgrader/tests/base/__init__.py, openwisp_firmware_upgrader/tests/base/test_models.py, openwisp_firmware_upgrader/tests/base/test_openwrt_upgrader.py, openwisp_firmware_upgrader/tests/base/test_tasks.py, openwisp_firmware_upgrader/tests/test_tasks.py, openwisp_firmware_upgrader/upgraders/openwrt.py, tests/openwisp2/sample_firmware_upgrader/tests.py
=> [upgrader] Retry on recoverable failures #23

openwisp_firmware_upgrader/tests/base/test_openwrt_upgrader.py, openwisp_firmware_upgrader/upgraders/openwrt.py
Further improvements which I found are needed during intensive testing:
- handled case in which the ip address changes
=> [openwrt] Futher improvements to upgrader

openwisp_firmware_upgrader/api/urls.py, openwisp_firmware_upgrader/api/views.py, openwisp_firmware_upgrader/tests/base/test_api.py
=> [api] Make firmware image not editable #47

.travis.yml, README.rst, openwisp_firmware_upgrader/api/urls.py, setup.py, tests/openwisp2/urls.py
=> [api] Move swagger to openwisp-utils #45

openwisp_firmware_upgrader/api/views.py, openwisp_firmware_upgrader/tests/base/test_api.py, openwisp_firmware_upgrader/tests/test_api.py, tests/openwisp2/sample_firmware_upgrader/tests.py
=>  [api] User spanning multiple orgs crashes the API #55

openwisp_firmware_upgrader/api/serializers.py, openwisp_firmware_upgrader/api/urls.py, openwisp_firmware_upgrader/api/views.py, openwisp_firmware_upgrader/tests/test_api.py
[fix] Made build_id in firmware image URLs readonly #56
Fixes #56
=> Made build_id in firmware image URLs readonly #56

.travis.yml, openwisp_firmware_upgrader/api/views.py, openwisp_firmware_upgrader/apps.py, openwisp_firmware_upgrader/tests/test_api.py, tests/openwisp2/settings.py
=> [api] Updated throttling implementation #63

openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/tests/test_admin.py
This solves #24.
So much trouble for 2 lines of code :man_facepalming:
=> [admin] Fixed bugged add action in DeviceFirmwareInline #24

.travis.yml, README.rst, openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/hardware.py, openwisp_firmware_upgrader/tests/test_admin.py, openwisp_firmware_upgrader/tests/test_models.py, requirements-test.txt, setup.py
=> [admin] Show in progress upgrade operation in Device Firmware tab #65

docker-compose.yml, openwisp_firmware_upgrader/templates/admin/upgrade_selected_confirmation.html
* [admin] Don't show the cancel button when there are no operations
* [docker] Add docker-compose for Redis
=> Minor improvements in admin and docker-compose

README.rst
* Remove zero width spaces
* Add /api/ to endpoints
* Fix typo
=> [readme] Small documentation fixes

openwisp_firmware_upgrader/tests/test_models.py, openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py
=> [tests] Fixed tests for celery>=4.4.3 #78

.travis.yml, tests/openwisp2/settings.py
=> [test] Use TimeLoggingTestRunner test runner

README.rst, openwisp_firmware_upgrader/api/urls.py, openwisp_firmware_upgrader/api/views.py, openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/tests/test_api.py
=> [api] Endpoint to know upgradeable devices in a mass upgrade operation

.gitignore, .travis.yml, openwisp_firmware_upgrader/api/urls.py, openwisp_firmware_upgrader/api/views.py, openwisp_firmware_upgrader/tests/test_admin.py, openwisp_firmware_upgrader/tests/test_api.py, requirements-test.txt, setup.py, tests/openwisp2/sample_firmware_upgrader/models.py, tests/openwisp2/sample_firmware_upgrader/tests.py
**Blocked by:** https://github.com/openwisp/openwisp-utils/pull/121
=> [deps] Add changes for isort 5.0

openwisp_firmware_upgrader/private_storage/views.py, openwisp_firmware_upgrader/tests/test_api.py, openwisp_firmware_upgrader/tests/test_private_storage.py
=> [private-storage] limit access to organization admin

.travis.yml, openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/migrations/0001_initial.py, openwisp_firmware_upgrader/tests/base.py, openwisp_firmware_upgrader/tests/test_admin.py, openwisp_firmware_upgrader/tests/test_api.py, openwisp_firmware_upgrader/tests/test_models.py, openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/tests/test_private_storage.py, setup.cfg, tests/openwisp2/sample_firmware_upgrader/migrations/0001_initial.py, tests/openwisp2/settings.py
Closes #92
**Blocked by:** https://github.com/openwisp/openwisp-controller/pull/220
=> [models] Swapper for openwisp-controller & openwisp-users #92

.travis.yml
=> [qa] Add Django 3.1 to build

README.rst, openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/tests/test_admin.py, openwisp_firmware_upgrader/tests/test_api.py, tests/openwisp2/settings.py, tests/openwisp2/urls.py
Added notification module (from openwisp-controller).
=> [change] Added notification module (from openwisp-controller)

openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/apps.py, openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/tasks.py
=> [fw-upgrader] Fix deprecation warnings #68

tests/openwisp2/sample_firmware_upgrader/admin.py, tests/openwisp2/sample_firmware_upgrader/tests.py
=> [qa] Add admin checks for details field #61

openwisp_firmware_upgrader/hardware.py
Pull Request to add more hardware in firmware upgrader module
Linksys & TP-Link & Raspberry & VMWare Virtual Appliance (x86_64)
=> [hardware] Add some TP-Link,Linksys,Raspberry,VMWare devices.

README.rst
The same instructions are there on openwisp-controller as well!
=> Removed duplicate setup instructions

.github/workflows/ci.yml
=> [ci] Fixed CI for django~=3.0.0 #134

.github/workflows/ci.yml, openwisp_firmware_upgrader/apps.py, openwisp_firmware_upgrader/tests/test_admin.py, requirements-test.txt, setup.py, tests/openwisp2/settings.py
Changes
Registered  Build, Category, and BatchUpgradeOperation models in a group name Firmware at position 100.
Checklist
closes #141
=> [enhancement] Registered menu groups #141

openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/static/admin/css/firmware-upgrader.css, openwisp_firmware_upgrader/templates/admin/firmware_upgrader/change_form.html
=> [fix] Fixed button style in build page

openwisp_firmware_upgrader/tests/test_admin.py
closes https://github.com/openwisp/openwisp-utils/issues/251
=> [test] Minor changes in test to fix failure

.github/workflows/ci.yml, .jshintrc, openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/static/firmware-upgrader/js/build.js, run-qa-checks
=> [enhancement] Use select2 for FirmwareImageInline type field #148

.github/workflows/ci.yml, README.rst, openwisp_firmware_upgrader/apps.py, setup.py, tests/openwisp2/sample_firmware_upgrader/apps.py, tests/openwisp2/urls.py
- Bumped django-private-storage~=3.0.0
Closes #159
=> [deps] Added support for Django 3.2 and 4.0 #159

openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/tests/test_admin.py
=> [fix] Saving a device admin with deleted DeviceFirmware object #70

openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/tests/test_selenium.py, requirements-test.txt, setup.py
=> [fix] Fixed restoring deleted device restores related objects #168 

README.rst, tests/openwisp2/settings.py
=> [tests] Added openwisp_ipam to test project #171 

openwisp_firmware_upgrader/tests/test_admin.py, openwisp_firmware_upgrader/tests/test_api.py
=> [tests] Fixed breaking tests due to openwisp-users #183

openwisp_firmware_upgrader/tasks.py
=> [change] Added time limits to celery tasks #177

openwisp_firmware_upgrader/api/urls.py
=> [change!] Made API url consistent with other OpenWISP modules #185

README.rst
Related to https://github.com/openwisp/openwisp-firmware-upgrader/issues/185.
=> [docs] Updated API endpoints in README

openwisp_firmware_upgrader/private_storage/urls.py, openwisp_firmware_upgrader/private_storage/views.py
=> [fix] Use "path" URL kwarg in "serve_private_file" URL pattern #197

CHANGES.rst, openwisp_firmware_upgrader/__init__.py
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
=> 1.0.1 release

openwisp_firmware_upgrader/base/models.py, openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, requirements-test.txt, setup.py, tests/openwisp2/settings.py
Use "DeviceConnection.get_working_connection" to establish a working connection with the device.
Closes #207
=> [change] Try all available DeviceConnection for performing upgrades #207

openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/filters.py, openwisp_firmware_upgrader/tests/test_admin.py
=> [feature] Switched to autocomplete filters #214

openwisp_firmware_upgrader/api/views.py
Depends on :
- https://github.com/openwisp/openwisp-users/pull/338
=> [chores] Used openwisp-users `ProtectedAPIMixin`

openwisp_firmware_upgrader/hardware.py
Added Ubiquiti AP Pro and AC Long Range.
=> [chores] Added Ubiquiti AP Pro and AC Long Range

openwisp_firmware_upgrader/hardware.py
=> [chores] Added ath79 Ubiquiti Unifi

openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/upgraders/openwrt.py
=> [fix] Fixed issues in reconnecting to device after firmware upgrade #235

.github/workflows/ci.yml, README.rst, openwisp_firmware_upgrader/__init__.py, openwisp_firmware_upgrader/apps.py, requirements-test.txt, setup.py, tests/openwisp2/sample_firmware_upgrader/__init__.py, tests/openwisp2/sample_firmware_upgrader/apps.py
- Dropped support for Python 3.7
- Dropped support for Django 4.0.0
- Bumped django-private-storage~=3.1.0
=> [deps] Added support for Django 4.1.0 and 4.2.0 

.github/workflows/ci.yml, tests/openwisp2/local_settings.example.py, tests/openwisp2/settings.py
Related to https://github.com/openwisp/openwisp-utils/pull/351 and https://code.djangoproject.com/ticket/32935.
=> [fix] Workaround for spatialite issue on Ubuntu 22.04 LTS

openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/widgets.py
Avoid manipulating private properties from Django.
=> [chores] Cleaned up media property methods

.github/workflows/ci.yml, openwisp_firmware_upgrader/admin.py, openwisp_firmware_upgrader/tests/test_admin.py
=> [fix] Admin actions require model permissions

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
=> [feature] Added the issue and pull request template #265

openwisp_firmware_upgrader/tests/test_api.py
Added support for djangorestframework<=3.15.1
=> [deps] Added compatibility for djangorestframework<=3.15.1

.github/workflows/pypi.yml, tests/openwisp2/settings.py
Closes #<issue-number>.
Please [open a new issue](https://github.com/openwisp/openwisp-firmware-upgrader/issues/new/choose) if there isn't an existing issue yet.
Please describe these changes.
Please include any relevant screenshots.
=> [deps/ci] django-allauth support and PyPI workflow 

docs/developer/installation.rst
=> [docs] Removed redundant "pip install -r requirements-test.txt"

requirements-test.txt, setup.py
=> [deps] Bumped openwisp-controller~=1.1.0

.github/workflows/version-branch.yml, CHANGES.rst, openwisp_firmware_upgrader/__init__.py, requirements-test.txt, setup.py
=> [ci] Added GitHub workflow to replicate commits to version branch

openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py
=> [tests] Added test for OpenWrt upgrader with -F and -n flags #291

openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/upgraders/openwrt.py
=> [feature] Added device recognition mechanism

CHANGES.rst, docs/user/settings.rst, openwisp_firmware_upgrader/__init__.py, openwisp_firmware_upgrader/tests/test_openwrt_upgrader.py, openwisp_firmware_upgrader/tests/test_selenium.py, runtests.py
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
---
All commits in the master branch since 1.1.1 tag: https://github.com/openwisp/openwisp-firmware-upgrader/compare/1.1.1...master
Commits included for the 1.1.2 release: https://github.com/openwisp/openwisp-firmware-upgrader/compare/1.1.1...release/1.1.2
=> 1.1.2 release

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/workflows/ci.yml, .github/workflows/pypi.yml
=> [qa] Formatted JS, YAML and markdown files
